//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Waste_management.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string FoodDescription { get; set; }
        public System.DateTime MaxPreserveTime { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> AssignedEmployeeId { get; set; }
        public string DistributionNotes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
